"""
File containing attack techniques for cracking ciphers. Currently
contains bruteforce attack.
"""

from typing import Set

import utilities as util
from cipher import Cipher


def bruteforce_attack(ciphertext: str, cipher: Cipher, max_key: int):
    """
    _summary_

    Args:
        ciphertext (str): Ciphertext to crack.
        cipher (Cipher): The cipher used to create the ciphertext.
        max_key (int): The largest key to test.

    Returns:
        Tuple[str, int]:
            A tuple; the first element is the best candidate generated
            (i.e. the best guess at the plaintext), and the second
            element is the key used to generate that candidate.
    """
    long_text = len(ciphertext) > 1024

    if (
        long_text
    ):  # When the text is long, we only use the first 1024 chars for scoring candidates.
        front_text = ciphertext[:1024]
        remaining_text = ciphertext[1024:]
        base_text = front_text
    else:  # Otherwise, use the whole text.
        base_text = ciphertext

    best_candidate = ""
    best_score = -1
    best_key = 0

    with open("wordlist.txt", "r") as word_list:
        word_set = {line.strip() for line in word_list.readlines()}

    for i in range(max_key):  # Try every key up to max_key
        plaintext = cipher.decrypt(base_text, i)
        score = _score_candidate(
            plaintext, word_set
        )  # Assess the text generated by the current key

        if score > best_score:
            best_score = score
            best_candidate = plaintext
            best_key = i

            _print_update(plaintext, ciphertext, i, max_key, best_score)

    if long_text:  # Use the generated key to encrypt the rest of the text.
        best_candidate += cipher.decrypt(remaining_text, best_key)

    return best_candidate, best_key


def _score_candidate(text: str, words: Set[str]) -> int:
    """
    Evaluate given text for relative likelihood of being the original
    plaintext by looking for valid English words.

    Args:
        text (str): Text to be evaluated/scored.
        words (Set[str]): The list of words to check for.

    Returns:
        int: An integer representing the score after evaluation.
    """
    score = 0

    for l in range(2, 45):
        for left_border in range(len(text) - l):
            right_border = left_border + l

            # Assumption: words in the word set are all lowercase
            substring = text[left_border:right_border].lower()

            if substring in words:
                score += (
                    len(substring) ** 2
                )  # Make longer words worth exponentially more for the score

    return score


def _print_update(plaintext, ciphertext, i, max_key, best_score):
    """
    Prints a status update for the brute force attack with current progress.
    """
    util.clear_screen()
    plaintext_preview = util.preview_text(plaintext)
    ciphertext_preview = util.preview_text(ciphertext)
    print(f"Brute force attack in progress...\n")
    print(f"Ciphertext:")
    print(f"--------------------------------------------------------------")
    print(ciphertext_preview)
    print(f"\n")
    print(f"Best plaintext candidate so far:")
    print(f"--------------------------------------------------------------")
    print(plaintext_preview)
    return
